CMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^manageclass/', include('manageclass.urls')),
]

manageclass/urls.py
from django.conf.urls import url
from . import views

app_name = 'manageclass'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^list$', views.student_list, name='list'),
    url(r'^(?P<student_number>[0-9]+)/$', views.student_requirements, name='requirement'),
    url(r'^(?P<student_number>[0-9]+)/detail$', views.student_detail, name='detail'),
    #url(r'^(?P<student_number>[0-9]+)/quizzes$', views.student_quizzes, name='quizzes'),
    #url(r'^(?P<student_number>[0-9]+)/tests$', views.student_tests, name='tests'),
    #url(r'^(?P<student_number>[0-9]+)/projects$', views.student_projects, name='projects'),
]

manageclass/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    student_number = models.IntegerField(primary_key=True)
    student_name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.student_number) + " - " + self.student_name

class Requirement(models.Model):
    student = models.ForeignKey(Student)
    REQ_TYPES = (
        ('Q', 'Quiz'),
        ('T', 'Test'),
        ('P', 'Project'),
    )
    requirement_type = models.CharField(max_length=1, choices=REQ_TYPES)
    raw_score = models.IntegerField()
    highest_possible_score = models.IntegerField()

    def __str__(self):
        return self.student.student_name + " " + self.requirement_type + " " + str(self.raw_score) + "/" + str(self.highest_possible_score)

manageclass/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from .models import *

# Create your views here.
def index(request):
    students = Student.objects.all()
    requirement = Requirement.objects.all()
    context = {
        'students': students,
        'requirement': requirement,
    }
    return render(request, 'manageclass/index.html', context)

def student_list(request):
    students = Student.objects.all()
    requirement = Requirement.objects.all()

    context = {
        'students': students,
        'requirement': requirement,
    }
    return render(request, 'manageclass/list.html', context)

def student_detail(request, student_number):
    student = Student.objects.get(pk=student_number)
    requirement = Requirement.objects.all()
    total_raw_quizzes = 0
    total_hps_quizzes = 0
    total_raw_tests = 0
    total_hps_tests = 0
    total_raw_projects = 0
    total_hps_projects = 0

    for r in requirement:
        if r.student.student_number == student.student_number:
            if r.requirement_type == 'Q':
                total_raw_quizzes += r.raw_score
                total_hps_quizzes += r.highest_possible_score
            elif r.requirement_type == 'T':
                total_raw_tests += r.raw_score
                total_hps_tests += r.highest_possible_score
            elif r.requirement_type == 'P':
                total_raw_projects += r.raw_score
                total_hps_projects += r.highest_possible_score

    if total_hps_quizzes != 0:
        q_ave = 20 * (total_raw_quizzes/total_hps_quizzes)      #Computes the average of quizzes
    else:
        q_ave = 0

    if total_hps_tests != 0:
        t_ave = 30 * (total_raw_tests/total_hps_tests)          #Computes the average of tests
    else:
        t_ave = 0

    if total_hps_projects != 0:
        p_ave = 50 * (total_raw_projects/total_hps_projects)    #Computes the average of projects
    else:
        p_ave = 0

    #Computes for the GWA o student
    gwa = q_ave + t_ave + p_ave

    #Checks the status of the student
    if gwa < 80:
        status = "Warning"
    else:
        status = "Good"

    context = {
        'student': student,
        'requirement': requirement,
        'total_raw_quizzes': total_raw_quizzes,
        'total_hps_quizzes': total_hps_quizzes,
        'total_raw_tests': total_raw_tests,
        'total_hps_tests': total_hps_tests,
        'total_raw_projects': total_raw_projects,
        'total_hps_projects': total_hps_projects,
        'gwa': gwa,
        'status': status,
    }

    return render(request, 'manageclass/details.html', context)

def student_requirements(request, student_number):
    student = get_object_or_404(Student, pk=student_number)
    requirement = Requirement.objects.all()

    context = {
        'student': student,
        'requirement': requirement,
    }

    return render(request, 'manageclass/requirement.html', context)

manageclass/templates/manageclass/details.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'manageclass/style.css' %}" />

<div class="container">
    <div class="back-to-list">
      <a href="{% url 'manageclass:list' %}"><span class="glyphicon glyphicon-menu-left"></span> B A C K</a>
    </div>
    <div class="profile-header">
      <h1>{{ student.student_name }}'s Profile</h1>
    </div>
    <div class="col-md-6">
      <div class="details">
        <h2>Name: {{ student.student_name }}</h4>
        <h2>Student Number: {{ student.student_number }}
        <h3>GWA: {{ gwa }}</h3>
        <h3>Status: {{ status }}
      </div>
    </div>
    <div class="col-md-6">
      <div class="details-picture">
        <div class="profile-detail-picture">

        </div>
      </div>
    </div>
    <!--<div class="col-md-6">
      <div class="details">
      <h2>Name:{{ student.student_name }}</h4>
      <h2>Student Number:&emsp;&nbsp;{{ student.student_number }}

      <h3>Requirements<h3>
      <h4>Quizzes</h4>
      <ol>
      {% for r in requirement %}
          {% if r.student.student_name == student.student_name and r.requirement_type == 'Q' %}
              <li>{{ r.raw_score }}/{{ r.highest_possible_score }}</li>
          {% endif %}
      {% endfor %}
      </ol>

      <h4>Tests</h4>
      <ol>
      {% for r in requirement %}
          {% if r.student.student_name == student.student_name and r.requirement_type == 'T' %}
              <li>{{ r.raw_score }}/{{ r.highest_possible_score }}</li>
          {% endif %}
      {% endfor %}
      </ol>

      <h4>Project</h4>
      <ol>
      {% for r in requirement %}
          {% if r.student.student_name == student.student_name and r.requirement_type == 'P' %}
              <li>{{ r.raw_score }}/{{ r.highest_possible_score }}</li>
          {% endif %}
      {% endfor %}
      </ol>


      </div>
    </div>-->
</div>

manageclass/templates/manageclass/index.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'manageclass/style.css' %}" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">

<body>
  <div class="container">

      <div class="app-name">
        <h1>CLASS MANAGEMENT SYSTEM</h1>
      </div>

      <div class="check-student-list">
          <a href="{% url 'manageclass:list' %}" class="student-button"><span class="glyphicon glyphicon-menu-right"></span></a>
      </div>

  </div>
</body>

manageclass/templates/manageclass/list.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'manageclass/style.css' %}" />
<div class="container">
    <div class="header">
      <h1>STUDENTS</h1>
    </div>
        {% for s in students %}
          <div class="col-sm-3">
            <div class="student-detail">
              <div class="profile-picture"></div>
              <div class="student-name">
                <a href="{% url 'manageclass:detail' s.student_number %}">{{ s.student_name }}</a>
              </div>
            </div>
          </div>
        {% endfor %}
</div>

manageclass/templates/manageclass/requirement.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% bootstrap_messages %}

{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'manageclass/style.css' %}" />
<div class="container">
  <div class="profile-header">
    <h1>{{ student.student_name }}'s Requirements</h1>
  </div>

  <div class="col-sm-4">
    <div class="quizzes">
      <h4>Quizzes</h4>
      {% for r in requirement %}
          {% if r.student.student_name == student.student_name and r.requirement_type == 'Q' %}
              {{ r.raw_score }}/{{ r.highest_possible_score }}
          {% endif %}
      {% endfor %}
    </div>
  </div>

  <div class="col-sm-4">
    <div class="tests">
      <h4>Tests</h4>

      {% for r in requirement %}
          {% if r.student.student_name == student.student_name and r.requirement_type == 'T' %}
              {{ r.raw_score }}/{{ r.highest_possible_score }}
          {% endif %}
      {% endfor %}
    </div>
  </div>

  <div class="col-sm-4">
    <div class="projects">
      <h4>Project</h4>

      {% for r in requirement %}
          {% if r.student.student_name == student.student_name and r.requirement_type == 'P' %}
              {{ r.raw_score }}/{{ r.highest_possible_score }}
          {% endif %}
      {% endfor %}
    </div>
  </div>
</div>